apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
  annotations:
    meta.helm.sh/release-name: piano-release
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP