apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"mongo-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"1Gi"},"hostPath":{"path":"/mnt/data"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"manual"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-07-14T12:53:13Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: mongo-pv
  resourceVersion: "146734"
  uid: e802f2ce-2cfa-4cb5-a710-22454d39b982
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo-pvc
    namespace: default
    resourceVersion: "146725"
    uid: b4b36e3e-8a72-4f15-9b63-d9ac88b778b5
  hostPath:
    path: /mnt/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-07-14T12:53:13Z"
  phase: Bound
