# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: "/mnt/data"



apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  annotations:
    meta.helm.sh/release-name: piano-release
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"