apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  annotations:
    meta.helm.sh/release-name: piano-release
    meta.helm.sh/release-namespace: default
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"mongo-pv"},"spec":{"capacity":{"storage":"1Gi"},"accessModes":["ReadWriteOnce"],"hostPath":{"path":"/mnt/data"}}}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"