apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongoDB.pv }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"