apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.NVCappName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
  type: LoadBalancer