apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"piano","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"piano"}},"template":{"metadata":{"labels":{"app":"piano"}},"spec":{"containers":[{"command":["/app/entrypoint.sh"],"env":[{"name":"MONGO_URL","value":"mongodb://shayshmaiser:PmRtpwEnX6CldTMb@mongodb-service:27017/bikorotDB"},{"name":"SDL_AUDIODRIVER","value":"dummy"},{"name":"SDL_VIDEODRIVER","value":"x11"},{"name":"DISPLAY","value":"host.docker.internal:0"}],"image":"shayshmaiser/piano-app:5.8","name":"piano","resources":{"requests":{"cpu":"100m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2024-07-15T13:00:27Z"
  generation: 1
  name: piano
  namespace: default
  resourceVersion: "239071"
  uid: 4632c701-b707-41d2-bd74-454d77bfd375
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: piano
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: piano
    spec:
      containers:
      - command:
        - /app/entrypoint.sh
        env:
        - name: MONGO_URL
          value: mongodb://shayshmaiser:PmRtpwEnX6CldTMb@mongodb-service:27017/bikorotDB
        - name: SDL_AUDIODRIVER
          value: dummy
        - name: SDL_VIDEODRIVER
          value: x11
        - name: DISPLAY
          value: host.docker.internal:0
        image: shayshmaiser/piano-app:5.8
        imagePullPolicy: IfNotPresent
        name: piano
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-15T13:00:28Z"
    lastUpdateTime: "2024-07-15T13:00:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-15T13:00:27Z"
    lastUpdateTime: "2024-07-15T13:00:28Z"
    message: ReplicaSet "piano-6f59b6cb97" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
